apiVersion: apps/v1
kind: Deployment
metadata:
  name: x-comm-api
  labels:
    app: x-comm-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: x-comm-api
  template:
    metadata:
      labels:
        app: x-comm-api
    spec:
      containers:
        - name: x-comm-api
          image: ecimionatto/x-comm-api:latest
          imagePullPolicy: Never
          env:
            - name: MONGODB_HOST
              value: mongodb
          ports:
            - containerPort: 8080