apiVersion: v1
kind: Service
metadata:
  name: x-comm-dashboard
  labels:
    run: x-comm-dashboard
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: x-comm-dashboard
